# Generated by Django 6.0.3 on 2026-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
